services:
  mysql:
    image: mysql:8
    ports:
      - '${MYSQL_PORT:-3307}:3306'
    environment:
      MYSQL_USER: 'app'
      MYSQL_PASSWORD: 'app'
      MYSQL_DATABASE: 'app'
      MYSQL_ROOT_PASSWORD: 'root'
  pgsql:
    image: postgres:14
    ports:
      - '${POSTGRES_PORT:-5432}:5432'
    environment:
      POSTGRES_USER: 'app'
      POSTGRES_PASSWORD: 'app'
      POSTGRES_DB: 'app'
